### ISSUE TITLE
BlobStoreTimeoutError should be supported for GCP

### ISSUE THREAD

**Issue by xbrianh** [chanzuckerberg/cloud-blobstore#17]
Unfortunately GCP does not provide straightforward timeout/retry configurations analogous to boto.

However, `google.cloud.storage` requests are forwarded all the way to the stdlib method `requests.Session().request`, which accepts a `timeout` keyword argument. Usage would look like:
```
import google.auth
import google.auth.transport.requests

connect_timeout = 1.0
read_timeout = 1.0
class Session(google.auth.transport.requests.AuthorizedSession):
    def request(self, *args, **kwargs):
        kwargs['timeout'] = (connect_timeout, read_timeout)
        return super().request(*args, **kwargs)

credentials, _ = google.auth.default()
gcp_client = Client(
    _http=Session(credentials)
)
```

The problem with this approach is Google may pull the rug out from under us by changing the `_http` argument:
>:param _http: (Optional) HTTP object to make requests. Can be any object
>                that defines ``request()`` with the same interface as
>                :meth:`requests.Session.request`. If not passed, an
>                ``_http`` object is created that is bound to the
>                ``credentials`` for the current object.
>                This parameter should be considered private, and could
>                change in the future.

Things are a bit more promising for retry behavior, which appears configurable through a global:
```
import google.resumable_media.common
google.resumable_media.common.MAX_CUMULATIVE_RETRY = 2
```

@ttung thoughts?

**Comment by ttung** [comment]
For tests, I think you can pass in a `_http` object that sets timeout, but then proxies to the normal requests library.

Catching the exception should be relatively straightforward, no?

**Comment by xbrianh** [comment]
Yes, it's straightforward. I just wanted to make sure we're comfortable with using the private `_http` parameter.
